### PR TITLE
Adding translations in endnotes 

### PR DESCRIPTION
**Pull request by jennfrye**
Primarily adding translations of French dialogue/phrases in the endnotes file with some typo correction and French-related formatting thrown in.

I have run both `se lint` and `se build --check-only`, and both came back clean except for the following (I didn't touch any of these files except for content.opf):

Code  ┃ Severity      ┃ File              ┃ Message                                                                  ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ f-003 │ Error         │ LICENSE.md        │ File does not match                                                      │
│       │               │                   │ /home/jenncf/.local/pipx/venvs/standardebooks/lib/python3.8/site-packag… │
├───────┼───────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ m-065 │ Error         │ content.opf       │ Word count in metadata doesn’t match actual word count.                  │
├───────┼───────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ f-004 │ Error         │ core.css          │ File does not match                                                      │
│       │               │                   │ /home/jenncf/.local/pipx/venvs/standardebooks/lib/python3.8/site-packag… │
├───────┼───────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ f-005 │ Error         │ logo.svg          │ File does not match                                                      │
│       │               │                   │ /home/jenncf/.local/pipx/venvs/standardebooks/lib/python3.8/site-packag… │
├───────┼───────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ f-014 │ Error         │ se.css            │ File does not match                                                      │
│       │               │                   │ /home/jenncf/.local/pipx/venvs/standardebooks/lib/python3.8/site-packag… │
├───────┼───────────────┼───────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ f-006 │ Error         │ uncopyright.xhtml │ File does not match                                                      │
│       │               │                   │ /home/jenncf/.local/pipx/venvs/standardebooks/lib/python3.8/site-packag… │
└

### CODE REVIEW

**Comment by acabal** [comment]
Hi Jenn, I can't merge this in because there are conflicts .Can you fix them before we continue?

You should also update your version of the toolset, which should make those lint errors go away.

Thanks!

**Comment by jennfrye** [comment]
> Hi Jenn, I can't merge this in because there are conflicts .Can you fix them before we continue?
> 
> You should also update your version of the toolset, which should make those lint errors go away.
> 
> Thanks!

I'm happy to! But I'm not sure how. Tutorials say to use the "Resolve conflicts" feature on GitHub, but I just see "This branch has no conflicts with the base branch." Can you point me in the right direction?

(Also, I uninstalled and reinstalled the toolset, and I'm still getting the same se lint errors.)

**Comment by acabal** [comment]
On your local copy, do something like:

```bash
git checkout master
git pull
git checkout <YOUR_BRANCH>
git rebase master
```

That should reveal any conflicts, which you can fix and push to this PR.

The specific error Github is showing me is: `This branch cannot be rebased due to conflicts`. So you can try searching that if the above doesn't work.

**Comment by jennfrye** [comment]
Okay, so I tried the lines you suggested, and it's just telling me "current branch jennfrye is up to date."

I found [this thread](https://stackoverflow.com/questions/56065077/github-tells-one-user-that-there-are-conflicts-but-not-the-other-user), which suggests that there may be a difference because I am trying to merge and you are trying to rebase. I think if I could switch it to rebase on my end, I could use the "Resolve conflicts" option to fix things, but from what I can tell I don't have permission to request a rebase PR. Are you able to accept the PR via merge instead? If not, I'll figure something else out.

**Comment by acabal** [comment]
Unfortunately Git can be really complicated and I just don't have the time to troubleshoot this further at the moment. Right now this repo can only accept rebased merges, so your local branch should start from the current tip of remote's (Github's) master. Github's master has at some point changed since you started, which is why there are conflicts and your local branch can't be rebased in. At least that's what I assume is going on.

So the outline of what you should do is: make sure your local master branch is up to date with Github's master. Then, rebase your work branch onto the up-to-date local master. Then, force push it into this PR. It maybe helpful to open your repo in a visual Git client, so you can see exactly how your work was interrupted by more commits to master in the meantime.

You can also try asking in the mailing list, they may be able to help more than I can at the moment.

**Comment by acabal** [comment]
I see you did a merge commit in 6d426920480a025511dc2039035e587bbf0be600 which is probably what's causing the problem. You should have rebased onto master, instead of creating a merge commit of master into your branch. Maybe if you try dropping that commit and rebasing back on, it will clear up. You can always make a copy of your repo folder somewhere else to restore in case things go sideways.

**Comment by jennfrye** [comment]
Thank you Alex! That should give me enough to work off of. It will take me awhile to work everything out, but I'll ping you when I think I've got it.

**Pull request closed without merging**
